### ISSUE TITLE
Omitting the query param for unit throws an error

### ISSUE THREAD

**Issue by rmx90210** [CityOfPhiladelphia/property2#102]
Deep linking to an address without specifying a unit throws `Uncaught TypeError: Cannot read property 'replace' of undefined`.

Example:
https://alpha.phila.gov/property/?a=1903%20GREEN%20ST

Might be related to 75f90eb.

**Comment by atogle** [comment]
Fixed by 73bf09886e5a0224dc37e78b50f16ae1e085fcdd.
