### ISSUE TITLE
No indication that "see more results" is doing anything

### ISSUE THREAD

**Issue by karissademi** [CityOfPhiladelphia/property2#110]
When a user clicks "see more results" there should be an indication that they have clicked the button and the page is attempting to load more data. This is somewhat related to https://github.com/CityOfPhiladelphia/property2/issues/7.

**Comment by michaelck** [comment]
@karissademi Are you looking to add a spinning icon type animation? Here's a branch where I've added and animated the font awesome spinner for the scenario described in #7:

https://github.com/CityOfPhiladelphia/property2/tree/loading-icon

**Comment by michaelck** [comment]
Closed in #132
