### ISSUE TITLE
"OPA Account" is inconsistently named

### ISSUE THREAD

**Issue by mjumbewu** [CityOfPhiladelphia/property2#124]
"OPA Account" on property 2, but "BRT Number" on the revenue site.

Maybe we should just say "OPA Account/BRT #" on property2.

**Comment by michaelck** [comment]
@mjumbewu checkout the opa-brt branch for a proposed solution. "OPA (BRT) Number" formatting used suggested by Liana. 

I was also thinking this could use a tooltip explanation... any thoughts on that?

**Comment by mjumbewu** [comment]
Closed by #134
