### ISSUE TITLE
Add an analytics event to tag recordings of OPA inquiry button use

### ISSUE THREAD

**Issue by rmx90210** [CityOfPhiladelphia/property2#128]
@laurenancona

**Comment by laurenancona** [comment]
#### Custom Analytics Event Attributes

**Added in GTM:** [Version 184](https://tagmanager.google.com/#/versions/accounts/31734588/containers/895129/versions/184)

**Trigger(s)**: `Click` where `element class="button"`
**URL Filters**: `begins with alpha.phila.gov/property`

| Attribute | Value |
| --- | --- |
| Category | Behavior |
| Action | {{ element text }} |
| Label | {{ value of data-hook }} |

**Reporting:** 
_(requires Phila.gov email address + access to Phila.gov property)_
1. Standard GA: Custom events appear under `Behavior > Events` in GA interface. Filter for the values above.
2. [Custom Report](https://analytics.google.com/analytics/web/template?uid=n5Z8cpMPRwK50PoKsDd91w) 

_Notes:_ This may take a few days to begin showing up in reports.
