### ISSUE TITLE
[ais] Unit search doesn't query AIS correctly

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/property2#145]
If you use the "unit" box on the new ais branch of property, it just appends the `unit` to the `address`, resulting in `1234 market st12`

**Comment by mjumbewu** [comment]
i pushed a fix for this (commit 0f5743625), but _maybe we should get rid of the unit box_, as it's now technically unnecessary (you can include the unit in the address box) and there are some addresses that won't be searchable through it, like "327 S 17th St, PH" (in ULRS, it looks like PH is a unit number, where as it's a unit type with no corresponding number in AIS).

**Comment by timwis** [comment]
Thanks. I would suggest leaving the unit box only because as a user, I would be a little confused about how to search for units and would probably assume it wasn't possible. Worth discussing as a group though
