### ISSUE TITLE
[ais] Latest valuation history missing

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/property2#147]
Compare "Valuation History" table [in production](http://property.phila.gov/?p=883309000) to [test version](http://property-test.surge.sh/?p=883309000) - it's missing the first row, for `2017`. That's because the Valuation Histories dataset in Socrata was not updated in March when the new values came out (there is no ETL process for that because it is somehow completely different from the regular delta updates that get made throughout the year).

Fortunately, the latest year exists in the regular "Property Assessments" dataset in Socrata. So the table will just need to have the first row retrieved from the first dataset.

**Comment by mjumbewu** [comment]
Looks like that dataset's already being used: https://github.com/CityOfPhiladelphia/property2/blob/ais/js/views/property.js#L381. It's just that some properties don't have the 2017 data in there: https://data.phila.gov/dataset/1234-Market-St-valuation/mjmt-m982

e.g., http://property-test.surge.sh/?p=882051215 has 2017 data

**Comment by timwis** [comment]
The "Valuation History" dataset contains several years of assessment history for each property. It gets updated twice weekly by delta updates. However, it _doesn't_ get updated en-masse each year when the _new assessments_ are created. As a result, the new 2017 values did not get added to all the properties in March. Since then, however, some 2017 values have been _updated_, so they show up in the dataset because of delta updates.

The latest values are always in the property assessment file, however, so we can use that to consistently display 2017 values.

This is indeed a weird quirk of the ETL process, but a necessary patch before we can switch over.

**Comment by mjumbewu** [comment]
So whatever the latest valuation is (e.g., for 2016) should be copied forward for all subsequent years?

**Comment by timwis** [comment]
Not exactly -- I'm about to submit a pull request to demonstrate.

**Comment by mjumbewu** [comment]
Fixed along with #151. Closes #150.
