### ISSUE TITLE
[ais] Table loses important label info while in mobile state 

### ISSUE THREAD

**Issue by michaelck** [CityOfPhiladelphia/property2#148]
Without labels the values lose their meaning.

<img width="374" alt="screen shot 2016-07-11 at 2 42 14 pm" src="https://cloud.githubusercontent.com/assets/1706901/16742498/e1f16360-4775-11e6-959a-f5cc04772f9f.png">
This screenshot taken in Chrome Version 51.0.2704.106 (64-bit) on OSX 10.11.4

**Comment by michaelck** [comment]
If you look at the branch @timwis created for issue #147, `147-latest-valuation`, notice that the first row now has labels in mobile view while the remaining rows do not:

<img width="380" alt="screen shot 2016-07-14 at 9 36 21 am" src="https://cloud.githubusercontent.com/assets/1706901/16841272/7d1e8ea8-49a6-11e6-8a85-f01b7837a2e4.png">

Because the first row of data (2017) comes from a different source (OPA) than the remaining rows, its markup is appended to the DOM earlier. It looks like tablesaw is appending the the label elements to the DOM sometime between the creation of the first row (2017) and the remaining rows.

**Comment by timwis** [comment]
@michaelck can you take a look again now that my PR has been cancelled? Still an issue?

**Comment by michaelck** [comment]
@timwis: This is still an issue. Your branch didn't cause it, but it helped identify the problem – tablesaw seems to be appending the table cell labels before property.js finishes appending the rows to the DOM

**Comment by michaelck** [comment]
Closed in #152
