### ISSUE TITLE
[ais] Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/property2#149]
On [this page](http://property-test.surge.sh/?p=882051215) I get the above console error twice, on lines 99 and 76 of property.js. It looks like `history.state.ais` is undefined when it's being accessed. The page just continues "loading."

**Comment by timwis** [comment]
I believe this occurs when `getHomestead()` is called before `getSaData()` completes, because `getSaData()` is what sets `history.state.ais`

**Comment by michaelck** [comment]
`getOpaData()` also depends on `getSaData()` setting `history.state.ais`.

I have a solution that uses the `.done` callback for the ajax request in both  `getOpaData()` and `getSaData()` to ensure that the data has returned before continuing on. Will commit shortly.

**Comment by timwis** [comment]
👍 nice! okay to close the issue then?

To deploy the latest version (with your changes), go into @rbrtmrtn's cloud9 and run:

``` bash
git pull origin ais
surge . -d property-test.surge.sh
```

**Comment by michaelck** [comment]
Sounds good to me. I've deployed to `property-test.surge.sh`
