### ISSUE TITLE
Let them view more results

### ISSUE THREAD

**Issue by gsf** [CityOfPhiladelphia/property2#15]
We need to provide functionality to view more results. OPA API displays total but defaults to limit of 30 hits -- can get the next set with the `skip` param. Search on "1420 Locust" is a good test.

**Comment by majshehab** [comment]
![screen shot 2015-04-08 at 11 48 34 am](https://cloud.githubusercontent.com/assets/4324930/7055052/b71e01a6-de0e-11e4-88cc-64ead2e99a26.png)
