### ISSUE TITLE
[ais] Valuation history data differs from OPA API

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/property2#151]
@mjumbewu noticed that the [assessment history](https://www.opendataphilly.org/dataset/opa-property-assessments/resource/6bc87f96-bf21-42ee-81fb-4efec307d1a0) dataset differs from the history in the OPA API in some cases. This must be because something went wrong in the delta update workflow that runs twice weekly. Perhaps it was down and missed some deltas, perhaps the deltas never made it over. The [dataset page](https://data.phila.gov/dataset/Properties-Assessment-Histories/a67f-xaf2/about) suggested it hadn't been updated in a month.

We ran it Tuesday and it appeared to work fine on its own, so not sure why it wasn't updating. Of course, this doesn't fix the discrepancies because it only runs on deltas. Perhaps there were no deltas for it to process when we ran it Tuesday?

Anyway, our plan is to truncate & load the dataset from `BRTPROD`'s `RECORDHISTORIES` table, which is what it was initially loaded from. That table also contains the `2017` values, so doing this will resolve #147 without the need for the hacky #150 solution as well.

**Comment by mjumbewu** [comment]
Looks like the data is pretty consistent now. Closing this issue, with a caveat that we should have a replacement process for the OPA data sooner rather than later.
