### ISSUE TITLE
[ais] Remove intersection option

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/property2#155]
This option doesn't work. If AIS doesn't support it, we should remove it from the interface, or provide a friendly error as to why it's disabled.

**Comment by michaelck** [comment]
Hey @timwis, I have a branch for this ready to go, but want to clarify: should the entire intersection logic be removed (references in `index.html`, `js/app.js`, & `js/views/results.js`) or should it simply be removed from the front end display (`index.html`)?

**Comment by timwis** [comment]
I think display would be fine since it may be added back in the future. Just want to confirm w/@mjumbewu or @rbrtmrtn that AIS doesn't support intersection search.

**Comment by mjumbewu** [comment]
It does not yet. I'll just display none or comment it out for now.

**Comment by rmx90210** [comment]
Closed by 7baf974de1fcd7e14f69f54bed729b54ea5d3cf9
