### ISSUE TITLE
[ais] Round recycling diversion rate to, say, two decimal places.

### ISSUE THREAD

**Issue by mjumbewu** [CityOfPhiladelphia/property2#156]
![image](https://cloud.githubusercontent.com/assets/146749/17281164/27f97ef4-5768-11e6-83fe-63342cb1ff0a.png)

**Comment by tswanson** [comment]
I vote for 1 decimal place. The page should have a % symbol also?

**Comment by mjumbewu** [comment]
Closed by bd211a2 and https://github.com/CityOfPhiladelphia/ais/commit/cf657685749ec366b6e65203c44a13a1affab22b
