### ISSUE TITLE
[ais] Errors are not handled if Socrata returns no results

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/property2#165]
If you search a property that AIS retrieves but Socrata has no records for, it throws a console error but doesn't display an error on the screen. It's because it tries to render `state.opa.xxxx` when `state.opa` is undefined.

**Comment by rmx90210** [comment]
This is the offending call:

https://github.com/CityOfPhiladelphia/property2/blob/ais/js/views/property.js#L147

We should probably do some checking here:

https://github.com/CityOfPhiladelphia/property2/blob/ais/js/views/property.js#L78
