### ISSUE TITLE
1234 Market St is not rendering the map

### ISSUE THREAD

**Issue by tswanson** [CityOfPhiladelphia/property2#167]

**Comment by rbrtmrtn** [comment]
This line is complaining that the `opa.shape` object is undefined;

https://github.com/CityOfPhiladelphia/property2/blob/ais/js/views/property.js#L248

**Comment by rmx90210** [comment]
This was fixed on the next ULRS run. OPA had changed the account number for 1234 MARKET ST and ULRS needed to catch up.
