### ISSUE TITLE
Owners overlapping mailing address

### ISSUE THREAD

**Issue by gsf** [CityOfPhiladelphia/property2#28]
Drop the font size or some other solution?

![screenshot 2015-04-02 at 21 19 11](https://cloud.githubusercontent.com/assets/151913/6976850/25fc7f16-d97e-11e4-81bb-eb5a1fde1e0e.png)

**Comment by gsf** [comment]
Think we still need to drop the font size or something.

![screenshot 2015-04-08 at 13 34 06](https://cloud.githubusercontent.com/assets/151913/7051150/1575ba84-ddf4-11e4-892f-eb39e56cb4a4.png)

**Comment by gsf** [comment]
That's for property 883056710 by the way.

**Comment by karissademi** [comment]
Fixed in commit b68ef1ec1c2b7b29bc259aed8dc4bcd38f3afeda
