### ISSUE TITLE
Panel header is the same type as its values

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/property2#34]
Maybe this belongs in the pattern portfolio repo, but just noticed that the header looks identical to the values. Example below.

![screen shot 2015-04-07 at 10 05 07](https://cloud.githubusercontent.com/assets/761444/7024890/dc9cc2ac-dd0d-11e4-8ebe-ae30c3177f66.png)

**Comment by gsf** [comment]
@kdemi @majshehab Thoughts?

**Comment by majshehab** [comment]
![screen shot 2015-04-07 at 11 33 42 am](https://cloud.githubusercontent.com/assets/4324930/7026636/f2708edc-dd18-11e4-9df6-94bc5752f42a.png)

^should be grey
