### ISSUE TITLE
Update search hint

### ISSUE THREAD

**Issue by gsf** [CityOfPhiladelphia/property2#36]
Hint should focus on 1234 market, and include an address-spanning example like "1200-1299 market".

**Comment by gsf** [comment]
Assigning @majshehab so we get the text right.

**Comment by majshehab** [comment]
@gsf @kdemi 

please add back text that said,
"￼￼Enter address, account number, intersection, or city block"

and change example text to, 
"e.g. 1234 Market Street, 883309000, 12th and Market, 1200-1299 Market"

**Comment by karissademi** [comment]
It's cool guys, I can take care of it.

**Comment by gsf** [comment]
One quick note on this as well is that "1200-1299 market" will return even numbers for that block while "1201-1299 market" will return odd. Tough to communicate that in a hint.

**Comment by majshehab** [comment]
hm.  ^ that should definitely be handled on our end, not the user's.  we're already asking enough of them to type out 00-99 :-1:

**Comment by gsf** [comment]
I think it would have to be modified at the API level. Looks like the "block" endpoint of the OPA API searches on both "1200-1298 market" and "1201-1299 market":
http://api.phila.gov/opa/v1.1/block/1234%20market/?format=json

**Comment by majshehab** [comment]
"1201-1299 market" just takes me to 1201 market street detail

**Comment by gsf** [comment]
Oh right because 1201 Market is the only property on that side of the block.

**Comment by gsf** [comment]
So that's a bad example. :confounded:
