### ISSUE TITLE
addresses not working without the word "street"

### ISSUE THREAD

**Issue by majshehab** [CityOfPhiladelphia/property2#56]
certain addresses don't work without the word "street" at the end of them. 

e.g. 1420 locust  vs. 1420 locust street   (or @kdemi said "1420 locust thing" also works!?)

^on that same note, units aren't returning (1420 locust street #6l)

**Comment by gsf** [comment]
The unit issue is being addressed in #21. The "1420 locust" oddity is an issue with the underlying API.

**Comment by gsf** [comment]
On further investigation this appears to be another symptom of #21.
