### ISSUE TITLE
Snazzier loading

### ISSUE THREAD

**Issue by gsf** [CityOfPhiladelphia/property2#7]
Maybe a nicer-looking thing when we're loading search results, etc.? Need some design input.

**Comment by timwis** [comment]
Note that at the moment, the `Loading...` text does not appear to be inside a row/column `<div>` and as such has no gutter on mobile

**Comment by michaelck** [comment]
The following branch may work for this issue. It's a CSS animated font awesome icon.

https://github.com/CityOfPhiladelphia/property2/tree/loading-icon

Motivated by #110. If this path forward is acceptable I can add a similar display on clicking "See more results".

**Comment by timwis** [comment]
you can preview @michaelck's branch at http://earthy-bikes.surge.sh

Looks nice. Another one I've used in the past is [nprogress](http://ricostacruz.com/nprogress/)

**Comment by timwis** [comment]
Although, @karissademi suggested a loading indicator pattern [was addressed](https://github.com/CityOfPhiladelphia/patterns/issues/25)?

**Comment by karissademi** [comment]
The pattern portfolio currently uses nprogress, but after discussing with @michaelck, we are going to change the loading pattern to solely rely on css.

**Comment by michaelck** [comment]
Helper class to animate the Font Awesome spinner icon has been added to patterns - http://cityofphiladelphia.github.io/patterns/#p-loading

**Comment by karissademi** [comment]
Helper class released in [Patterns 1.2.0](https://github.com/CityOfPhiladelphia/patterns/releases/tag/1.2.0).

**Comment by michaelck** [comment]
Closed in #126
