### ISSUE TITLE
Valuation history showing no records

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/property2#71]
Viewing this property on mobile shows no results in valuation histories table. Also, table is not responsive, increases screen width and enables horizontal scrolling. Did we ever implement the css-based responsive tables? https://alpha.phila.gov/property/?p=881618310

**Comment by timwis** [comment]
![screenshot_2015-05-31-14-13-15](https://cloud.githubusercontent.com/assets/761444/7903112/15c6d5a6-07a0-11e5-93c5-c48a62b20b27.png)

**Comment by gsf** [comment]
The table is responsive on my laptop but not on my phone. Thoughts, @kdemi?

Despite the horizontal scrolling I am seeing records on my phone. Can you reproduce the missing data display, @timwis?

**Comment by karissademi** [comment]
The table is responsive, but it takes about 15 seconds before the javascript loads and re-renders the table. I can look into improving the speed on that, but I think we wanted to have a bigger conversation about how responsive tables should work across the board. I can make an issue on the pattern portfolio addressing that.

**Comment by atogle** [comment]
This may also be a good opportunity to explore some other ways of handling tables on mobile.

**Comment by timwis** [comment]
I've used some of [these examples](http://elvery.net/demo/responsive-tables/) before but came across [this one](http://codepen.io/anon/pen/QwPVNW) a couple months ago which seems most elegant. It may be the case that "flip scroll" makes more sense in some cases and "convert to rows" makes more sense in others.

**Comment by mjumbewu** [comment]
This issue seems resolved by the latest updates to the app. Is that not the case @karissademi ?
