### ISSUE TITLE
Non-HTTPS script being loaded

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/property2#72]
Looks like google tag manager is trying to load a non `https` script and it's being blocked with a console error. Not breaking anything, just an FYI. /cc @laurenancona 

![screen shot 2015-06-10 at 12 58 44](https://cloud.githubusercontent.com/assets/761444/8088611/94e145ba-0f70-11e5-883e-4e239ad3980b.png)

**Comment by gsf** [comment]
We're seeing this on all pages of alpha.phila.gov.

**Comment by gsf** [comment]
@laurenancona Still seeing this on alpha.

![screenshot 2015-06-18 at 13 47 18](https://cloud.githubusercontent.com/assets/151913/8237971/e077c8cc-15c0-11e5-90a6-3db8c1114697.png)

**Comment by laurenancona** [comment]
Weird, I thought I killed anything that might be calling that. Checking again.

**Comment by timwis** [comment]
Appears resolved, but now there's a new, similar issue
