### ISSUE TITLE
API responses with no data not handled

### ISSUE THREAD

**Issue by rmx90210** [CityOfPhiladelphia/property2#76]
I'm getting an `Uncaught TypeError: Cannot read property 'property' of undefined` on line 37 of `results.js` at 

https://alpha.phila.gov/property/?q=182142620

Spoke to Andrey about this -- if you search for an account that doesn't exist, the OPA API will return 200 or 400 based on whether the search has been cached or not. However in both cases the JSON will have a "code" of 400.

**Comment by gsf** [comment]
Good catch, @rbrtmrtn, and thanks for the report.
