### ISSUE TITLE
Non HTTPS tiles being loaded for map

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/property2#78]
In case you're not already aware, it's loading images from non HTTPS endpoints. 
<img width="447" alt="screen shot 2015-08-06 at 08 07 56" src="https://cloud.githubusercontent.com/assets/761444/9111193/602a5770-3c12-11e5-935c-b5cdb2e4eda4.png">

**Comment by gsf** [comment]
I believe @atogle is aware of this issue. HTTPS isn't currently supported by the arcgis server, but GSG is planning to turn it on soon.

**Comment by atogle** [comment]
Fixed by ea98a4752e449f3e73bcf771e0bd79d2ac00a87e.
