### ISSUE TITLE
Owner search on mobile should show owner name in results list

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/property2#84]
Currently it shows address & market value but not owner name, so for a query like "smith," you'd have to check each listing to determine if it's the right smith.

<img width="300" alt="screen shot 2015-08-28 at 15 26 19" src="https://cloud.githubusercontent.com/assets/761444/9555127/36a5b23a-4d99-11e5-9008-fdc694a58bf6.png">

**Comment by atogle** [comment]
Fixed with 9fa1ef9aa4c5b4aee18ef3cfb201dfe0d786db22.
