### ISSUE TITLE
Clarification of "safe and responsible use" message when searching by owner

### ISSUE THREAD

**Issue by davewalk** [CityOfPhiladelphia/property2#86]
I wanted to see if it would be possible to get some clarification on "safe and responsible use" message that is shown when searching by owner. This message is vague as the terms "safe" and "responsible" are open to interpretation if not explained further.

While your Privacy Policy states your allowance of storing this personally identifiable information, it does not disclose these terms of usage in regards to the message in question. Apologies if I have missed that somewhere.

What are the specific metrics in which usage of the search by owner tool is not considered "safe and responsible"? What actions will occur if there is usage that is considered not "safe and responsible"?

Thanks!

**Comment by timwis** [comment]
Hi Dave, we log requests to the OPA API. This includes the date/time, IP address, and endpoint hit, which includes the query. There are no use limitations around what you do with the data you get back. We're just logging that you accessed it (as every web server on the internet does).

**Comment by davewalk** [comment]
I realize that the City is logging requests and I understand that every web server does this. However, this is the only web application I've ever seen that displays the IP address of the user with a message that this issue is about.

The point of the issue is that the message is unclear and implies some action that isn't clarified in legal terms of a Terms of Service or Privacy Policy. It's not about the City storing the IP address and other information, but what the message implies in vague terms.

If there is no point to the message, I would suggest removing it because it could confuse the user unnecessarily as it has me.

Thanks!

**Comment by timwis** [comment]
Thanks Dave. Pointing out that we're keeping a record was part of what we felt we needed to do to provide search by owner functionality responsibly. The tooltip was our best shot at explaining that in a concise way to users, but we're certainly open to alternative copy.

**Comment by timwis** [comment]
Oh I see what you're saying, perhaps the tooltip is more vague and worrisome than the IP/timestamp itself. I suppose we could remove the tooltip if we felt no explanation was necessary.

**Comment by davewalk** [comment]
I'm still not seeing a use for either the message or the tooltip. If there isn't one, I'd suggest getting rid of both of them. If you aren't doing anything outside of the bounds of your Privacy Policy with the data then they are unnecessary and could be confusing.

Thanks!

**Comment by timwis** [comment]
We need to keep the message there for owner searches but can rework the tooltip or remove that. I'll check in with our content team. Thanks!
