### ISSUE TITLE
Deal with LOOP

### ISSUE THREAD

**Issue by gsf** [CityOfPhiladelphia/property2#9]
If we launch before July we'll have to handle the Tax LOOP (see current property.phila.gov). On address page load we should determine eligibility and stick some text on the page. If it is eligible, the link should raise a modal displaying the form.

(For this and all modal needs see http://foundation.zurb.com/docs/components/reveal.html).

**Comment by atogle** [comment]
LOOP will not be supported in Property2, per the Revenue Department.
