### ISSUE TITLE
Hover background in list results is the same as even rows

### ISSUE THREAD

**Issue by gsf** [CityOfPhiladelphia/property2#96]
The hover background color should be different from the background for both odd and even rows. As it stands, it isn't good feedback for the user. Screenshot:

![screenshot 2016-02-02 at 16 18 43](https://cloud.githubusercontent.com/assets/151913/12764642/014b8388-c9c9-11e5-830c-4bf6f7f0e22c.png)

**Comment by mjumbewu** [comment]
Closed by #106
